# Generated by Django 4.2.23 on 2025-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('encrypted_content', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('detected_emotions', models.JSONField(blank=True, null=True)),
                ('ai_prompt_used', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.user')),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
