# Generated by Django 4.2.23 on 2025-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endurance_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('level_name', models.CharField(choices=[('Annamaya', 'Annamaya - Physical'), ('Pranamaya', 'Pranamaya - Energy'), ('Manomaya', 'Manomaya - Mental'), ('Vijnanamaya', 'Vijnanamaya - Wisdom'), ('Anandamaya', 'Anandamaya - Bliss')], default='Annamaya', max_length=50)),
                ('daily_streak', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.user')),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.JSONField(default=list, help_text='Array of user goals')),
                ('stress_level', models.CharField(blank=True, choices=[('several_times_daily', 'Several times daily'), ('daily', 'Daily'), ('few_times_week', 'Few times a week'), ('rarely', 'Rarely')], max_length=50, null=True)),
                ('aspirational_goals', models.JSONField(default=list, help_text='Desired states')),
                ('age_group', models.CharField(blank=True, choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
