# Generated by Django 4.2.23 on 2025-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundscapeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('focus', 'Focus'), ('relaxation', 'Relaxation'), ('sleep', 'Sleep')], max_length=50)),
                ('subcategory', models.CharField(choices=[('binaural_beats', 'Binaural Beats'), ('nature_sounds', 'Nature Sounds'), ('classical', 'Classical')], max_length=50)),
                ('audio_url', models.URLField(max_length=500)),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'soundscape_content',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundscape.soundscapecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_activities', to='accounts.user')),
            ],
            options={
                'db_table': 'user_playlist_activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
